### ISSUE TITLE
Cambiar el id por defecto de la oferta de trabajo por un id que incremente su valor de 1 en 1

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#10]
Ahora que ya tenemos el esquema con los requerimientos del Front-end nos queda poner un id mas legible
debido a que mongoDB no tiene una keyword de AUTOINCREMENT como en bases de datos relacionales debemos programarlos nosotros o servirnos de herramientas.

Para esto podemos usar triggers, hacer uso de librerias o programacion pura dejo recursos utiles para quien se quiera hacer cargo de esta tarea

**Comment by pieropr2k** [comment]
lo implemente con la libreria mongoose-sequence

**Comment by Andres2310** [comment]
perfecto Piero todo funciona y Sebastian añade la logica en la ruta
