### ISSUE TITLE
Mejorar la implementación de las rutas en el proyecto

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#11]
Ya hicimos la funcionalidad básica de la API pero aun falta gestionar las rutas y los controladores. La persona encargada de esto creara la carpeta routes y creara el archivo jobs para la ruta que ya gestionamos al principio

```
-routes
   └ jobs.js
```

**Comment by codewithsebas** [comment]
Inicio de desarrollo

**Comment by codewithsebas** [comment]
Actualización de las rutas con su respectiva carpeta routes y archivo jobs.js, y actualización de /jobs/idOffer -> para la ruta Frontend

**Comment by Andres2310** [comment]
Bien Sebastián y gracias por arreglar la ruta de ID con la nueva lógica del negocio
