### ISSUE TITLE
Añadir Controladores

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#12]
añadir controlador básico para las nuevas rutas establecidas creando la carpeta controllers y un archivo controllerJobs.js
```
controllers
    └controllerJobs.js
```

**Comment by codewithsebas** [comment]
Actualización de controlador finalizado con sus rutas respectivas

**Comment by Andres2310** [comment]
bien hecho Sebas, efectividad
