### ISSUE TITLE
Implementar CRUD en la API

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#13]
Implementar DELETE, UPDATE, PATCH para incrementar funcionalidad

**Comment by pieropr2k** [comment]
yo hago el patch

**Comment by codewithsebas** [comment]
Delete y Update broo!

**Comment by Dev-Juniorr** [comment]
Bro ya acabe ya hice el Push

**Comment by Andres2310** [comment]
@pieropr2k se encarga de Patch y hara la prueba de logica en index.js
@Dev-Juniorr se encargara de Delete y Update y hara la prueba de logica en carpeta controlers y archivo controllerJobs.js

**Comment by codewithsebas** [comment]
Inicio con las nuevas rutas de update y delete depende de la id que mongo nos da

**Comment by codewithsebas** [comment]
Rutas añadidas en la carpeta Routes -> jobs.js | Update y Delete añadidas para la Api

**Comment by codewithsebas** [comment]
Todo funcionando a la perfección, tarea dada por finalizada!

**Comment by Andres2310** [comment]
Buenisima chicos, muchas gracias
