### ISSUE TITLE
añadir los controladores y rutas de DELETE, PATCH y UPDATE

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#14]
Trabajar en la carpeta controlador hasta que la carpeta rutas sea actualizada apropiadamente

**Comment by Andres2310** [comment]
Piero se encarga de los controladores y añadir la lógica que implemento en las rutas @Dev-Juniorr

**Comment by pieropr2k** [comment]
Para hacer peticiones en PATCH, tendrian que considerar que si se quieren modificar los atributos que continen arrays o objetos, ejemplo los atributos "languages" y "company" ahi se tendria que hacer la peticion en formato JSON
Si se quiere modificar los atributos que solo contienen strings o booleanos, por ejemplo "level", ahi tiene que hacer la peticion en formato TXT-Plain

**Comment by Andres2310** [comment]
Gracias Piero tendremos en cuenta eso para escalar el proyecto a futuro, buen trabajo
