### ISSUE TITLE
Cambiar los endpoints segun el nuevo esquema de hoy

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/portal-de-empleo-API#7]
Debido al nuevo JSON base, el esquema de la base datos cambio y también se debe actualizar los endpoints que se hicieron para obtener y actualizar datos.

**Comment by pieropr2k** [comment]
ya se comenzó

**Comment by Andres2310** [comment]
end points actualizados correctamente, muchas gracias Piero
